// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idvgmrrawcobcfnrbifz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkdmdtcnJhd2NvYmNmbnJiaWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExOTM5MTAsImV4cCI6MjA1Njc2OTkxMH0.Tocgb-XET9g9ALOUZ52xQUeyDY1M0gn3KtLySqUXIGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);